import { Package, DollarSign, Box, Tag, Image } from 'lucide-react'
import { EntityFormConfig } from '../types'

export const productFormVariation: EntityFormConfig = {
  mode: 'create',
  layout: 'grid',
  columns: 2,
  fieldSpacing: 'md',
  submitButtonText: 'Create Product',
  cancelButtonText: 'Cancel',
  validateOnChange: true,
  validateOnBlur: true,
  showProgress: true,

  fields: [
    {
      name: 'name',
      label: 'Product Name',
      type: 'text',
      placeholder: 'Enter product name',
      required: true,
      icon: Package,
      minLength: 3,
      maxLength: 200,
    },
    {
      name: 'sku',
      label: 'SKU',
      type: 'text',
      placeholder: 'PROD-001',
      required: true,
      icon: Tag,
      pattern: '^[A-Z0-9-]+$',
      helpText: 'Unique product identifier (uppercase, numbers, hyphens)',
    },
    {
      name: 'category',
      label: 'Category',
      type: 'select',
      placeholder: 'Select category',
      required: true,
      options: [
        { label: 'Electronics', value: 'electronics' },
        { label: 'Clothing', value: 'clothing' },
        { label: 'Home & Garden', value: 'home-garden' },
        { label: 'Sports & Outdoors', value: 'sports-outdoors' },
        { label: 'Books & Media', value: 'books-media' },
      ],
    },
    {
      name: 'brand',
      label: 'Brand',
      type: 'text',
      placeholder: 'Brand name',
    },
    {
      name: 'price',
      label: 'Price',
      type: 'number',
      placeholder: '0.00',
      required: true,
      icon: DollarSign,
      min: 0,
      step: 0.01,
    },
    {
      name: 'discountPrice',
      label: 'Sale Price',
      type: 'number',
      placeholder: '0.00',
      icon: DollarSign,
      min: 0,
      step: 0.01,
      helpText: 'Leave empty if not on sale',
    },
    {
      name: 'stock',
      label: 'Stock Quantity',
      type: 'number',
      placeholder: '0',
      required: true,
      icon: Box,
      min: 0,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      placeholder: 'Select status',
      required: true,
      options: [
        { label: 'Active', value: 'active' },
        { label: 'Draft', value: 'draft' },
        { label: 'Out of Stock', value: 'out-of-stock' },
        { label: 'Discontinued', value: 'discontinued' },
      ],
    },
    {
      name: 'description',
      label: 'Description',
      type: 'textarea',
      placeholder: 'Enter product description...',
      required: true,
      rows: 4,
      maxLength: 1000,
    },
    {
      name: 'features',
      label: 'Key Features',
      type: 'textarea',
      placeholder: 'One feature per line...',
      rows: 3,
      helpText: 'Enter each feature on a new line',
    },
    {
      name: 'tags',
      label: 'Tags',
      type: 'text',
      placeholder: 'wireless, premium, bestseller',
      helpText: 'Comma-separated tags for better searchability',
    },
    {
      name: 'weight',
      label: 'Weight (kg)',
      type: 'number',
      placeholder: '0.0',
      min: 0,
      step: 0.1,
    },
    {
      name: 'dimensions',
      label: 'Dimensions (L x W x H cm)',
      type: 'text',
      placeholder: '10 x 5 x 2',
    },
    {
      name: 'image',
      label: 'Product Image',
      type: 'file',
      icon: Image,
      helpText: 'Upload product image (JPG, PNG, max 5MB)',
    },
    {
      name: 'featured',
      label: 'Featured Product',
      type: 'switch',
      helpText: 'Display this product on the homepage',
    },
    {
      name: 'allowReviews',
      label: 'Allow Customer Reviews',
      type: 'switch',
    },
  ],
}

export default productFormVariation
