import { User, Mail, Phone, Lock, Shield, Calendar } from 'lucide-react'
import { EntityFormConfig } from '../types'

export const userFormVariation: EntityFormConfig = {
  mode: 'create',
  layout: 'grid',
  columns: 2,
  fieldSpacing: 'md',
  submitButtonText: 'Create User',
  cancelButtonText: 'Cancel',
  validateOnChange: true,
  validateOnBlur: true,
  showProgress: true,

  fields: [
    {
      name: 'name',
      label: 'Full Name',
      type: 'text',
      placeholder: 'Enter full name',
      required: true,
      icon: User,
      minLength: 2,
      maxLength: 100,
    },
    {
      name: 'email',
      label: 'Email Address',
      type: 'email',
      placeholder: 'user@example.com',
      required: true,
      icon: Mail,
      validation: [
        { type: 'email', message: 'Please enter a valid email address' },
      ],
    },
    {
      name: 'phone',
      label: 'Phone Number',
      type: 'tel',
      placeholder: '+1 (555) 123-4567',
      icon: Phone,
      pattern: '^[\\d\\s\\-\\+\\(\\)]+$',
    },
    {
      name: 'username',
      label: 'Username',
      type: 'text',
      placeholder: 'username',
      required: true,
      minLength: 3,
      maxLength: 30,
      pattern: '^[a-zA-Z0-9_]+$',
    },
    {
      name: 'password',
      label: 'Password',
      type: 'password',
      placeholder: '••••••••',
      required: true,
      icon: Lock,
      minLength: 8,
      pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)',
      helpText: 'At least 8 characters with uppercase, lowercase, and numbers',
    },
    {
      name: 'confirmPassword',
      label: 'Confirm Password',
      type: 'password',
      placeholder: '••••••••',
      required: true,
      icon: Lock,
    },
    {
      name: 'role',
      label: 'Role',
      type: 'select',
      placeholder: 'Select role',
      required: true,
      icon: Shield,
      options: [
        { label: 'Administrator', value: 'admin' },
        { label: 'Manager', value: 'manager' },
        { label: 'User', value: 'user' },
        { label: 'Guest', value: 'guest' },
      ],
    },
    {
      name: 'status',
      label: 'Account Status',
      type: 'select',
      placeholder: 'Select status',
      required: true,
      options: [
        { label: 'Active', value: 'active' },
        { label: 'Inactive', value: 'inactive' },
        { label: 'Suspended', value: 'suspended' },
      ],
    },
    {
      name: 'joinedDate',
      label: 'Join Date',
      type: 'date',
      icon: Calendar,
    },
    {
      name: 'permissions',
      label: 'Permissions',
      type: 'multiselect',
      placeholder: 'Select permissions',
      options: [
        { label: 'Read', value: 'read' },
        { label: 'Write', value: 'write' },
        { label: 'Delete', value: 'delete' },
        { label: 'Admin', value: 'admin' },
      ],
    },
    {
      name: 'bio',
      label: 'Biography',
      type: 'textarea',
      placeholder: 'Tell us about yourself...',
      rows: 4,
      maxLength: 500,
    },
    {
      name: 'notifications',
      label: 'Enable Notifications',
      type: 'switch',
      helpText: 'Receive email notifications for important updates',
    },
  ],
}

export default userFormVariation
