import { FieldConfig } from "@/components/entityManager";
import { DAY_OF_WEEK_LABELS } from "../../types";

export const classGroupScheduleFields: FieldConfig[] = [
  {
    name: "timetable",
    label: "Timetable",
    type: "select",
    required: true,
    placeholder: "Select timetable",
    helpText: "The timetable this schedule belongs to",
    endpoint: "/api/v1/logx/timetabling/timetables/",
    displayField: "name",
    valueField: "id",
  },
  {
    name: "class_group",
    label: "Class Group",
    type: "select",
    required: true,
    placeholder: "Select class group",
    helpText: "The class group for this schedule",
    endpoint: "/api/v1/institution/class-groups/",
    displayField: "name",
    valueField: "id",
  },
  {
    name: "unit",
    label: "Unit",
    type: "select",
    required: true,
    placeholder: "Select unit",
    helpText: "The subject/unit being taught",
    endpoint: "/api/v1/academics/units/",
    displayField: "name",
    valueField: "id",
  },
  {
    name: "instructor",
    label: "Instructor",
    type: "select",
    required: true,
    placeholder: "Select instructor",
    helpText: "The teacher/instructor for this class",
    endpoint: "/api/v1/accounts/staff/",
    displayField: "full_name",
    valueField: "id",
  },
  {
    name: "room",
    label: "Room",
    type: "select",
    required: true,
    placeholder: "Select room",
    helpText: "The room where the class will be held",
    endpoint: "/api/v1/logx/resources/rooms/",
    displayField: "name",
    valueField: "id",
  },
  {
    name: "day_of_week",
    label: "Day of Week",
    type: "select",
    required: true,
    placeholder: "Select day",
    helpText: "The day of the week for this class",
    options: Object.entries(DAY_OF_WEEK_LABELS).map(([value, label]) => ({
      value: parseInt(value),
      label,
    })),
  },
  {
    name: "start_time",
    label: "Start Time",
    type: "time",
    required: true,
    placeholder: "e.g., 08:00",
    helpText: "Class start time",
  },
  {
    name: "end_time",
    label: "End Time",
    type: "time",
    required: true,
    placeholder: "e.g., 09:00",
    helpText: "Class end time",
  },
  {
    name: "is_locked",
    label: "Lock Schedule",
    type: "checkbox",
    helpText: "Prevent this schedule from being modified by the timetable generator",
  },
  {
    name: "notes",
    label: "Notes",
    type: "textarea",
    placeholder: "Additional notes about this schedule...",
    helpText: "Any additional information or special instructions",
  },
];
